/**
 * 估值曲线下方的口头禅。
 *
 * 按情境分桶，运行时只从匹配的桶里抽一句。
 * 想加句子：丢进对应数组即可，不必改别的代码。
 *
 * 桶：
 *   rising / flat / slow  相对近几天的节奏
 *   overwork              今天已经投很多，该歇
 *   play                  短视频/游戏过久
 *   empty / waste / weekend
 *   dawn morning noon afternoon evening night  一天里的钟点
 *   books.mind / body / craft  分栏加味
 */

function hashPick(pool, seed) {
  if (!pool.length) return "";
  let h = 2166136261;
  for (let i = 0; i < seed.length; i++) {
    h = Math.imul(h ^ seed.charCodeAt(i), 16777619);
  }
  return pool[Math.abs(h) % pool.length];
}

function timeBucket(hour) {
  if (hour < 5) return "night";
  if (hour < 8) return "dawn";
  if (hour < 11) return "morning";
  if (hour < 14) return "noon";
  if (hour < 18) return "afternoon";
  if (hour < 22) return "evening";
  return "night";
}

function resolveMood(evalKey, todayH, consumeH) {
  if (evalKey === "empty") return "empty";
  if (consumeH >= 2.5 && consumeH >= todayH) return "play";
  if (todayH >= 6) return "overwork";
  if (evalKey === "rising" && todayH >= 5) return "overwork";
  return evalKey || "flat";
}

const LINES = {
  zh: {
    rising: [
      "最近表现不错，今晚必须加鸡腿。",
      "加仓了啊？行，今晚的奶茶算你赢的。",
      "曲线在抬头，你也该抬头挺胸了。",
      "比前两天狠，这个势头留着，别明天就散。",
      "行情在加速。不是玄学，是你自己干的。",
      "漂亮。记得把功劳记在自己头上，别谦虚。",
      "今天这份狠劲，值得一盘鸡腿，不加辣也行。",
      "曲线比人诚实：你最近是真的在做事。",
      "加了仓就别装淡定，今晚可以小小得意一下。",
      "投入变多了。市场看见了，你自己更该看见。",
      "这波是你自愿加班给未来的，未来会记得。",
      "比昨天多那么一截，已经够资格奖励自己。",
      "加速了。别问值不值，先把鸡腿吃了。",
      "你最近有点发光，不是滤镜，是时长。",
      "持仓变沉了，人也该挺直一点。",
      "加仓成功。请用一顿好的收尾，别用短视频。",
      "今天你对得起这根往上的线。",
      "比近几天勤快，估值在鼓掌，小声的那种。",
      "行情热了。热完记得喝水，别只热头。",
      "多出来的那一小时，比任何鸡汤都响。",
      "你最近不是运气好，是手没停。",
      "曲线上扬，心情也可以上扬，允许的。",
      "加了就加了。今晚的电影票，自己请自己。",
      "这叫主动进攻，不是偶然闪光。",
      "比节奏快一截。保持，别表演性加班。",
      "估值在加速，胃也该加速：去吃饭。",
      "干得可以。小小炫耀一下，房间里没人看见。",
      "今天的你，比昨天的你更像一回事。",
      "投入加码了。奖励可以有，自满就免了。",
      "这根线在说：你没有骗自己。",
      "最近顺。顺的时候最容易松，你知道的。",
      "加仓是真的，鸡腿也是真的，去吃。",
      "比均值高出一截，这叫实力，不叫玄学。",
      "你把自己当资产养了，资产当然涨。",
      "今晚加鸡腿。不加也行，但态度要有。",
      "涨了。不是别人抬轿，是你自己走的。",
      "这波行情的主角，就是坐在这儿的你。",
      "多干的那些，以后会变成很便宜的后悔药。",
      "加速通道打开了。别急着关，也别通宵。",
      "今天配得上一句「可以啊你」。",
    ],
    flat: [
      "和最近节奏差不多，不算飞跃，也不算躺平。",
      "原速前进。无聊，但复利就爱这种无聊。",
      "今天没有名场面，有的是该做的事。",
      "平盘。平盘不可耻，断了才可耻。",
      "维持住了。英雄联盟看的是连胜，这里看的是不断。",
      "既没加仓也没跑路，这叫成年人的稳定。",
      "曲线在走平常路。平常路才能走很远。",
      "和近几天一个样。样虽然平，命还在。",
      "没爆发，也没塌方。及格以上，继续。",
      "今天是标准件。标准件堆多了就是资产。",
      "节奏没变。变的是：你又撑过了一天。",
      "平，但还在。很多故事死在「还不在」。",
      "按原速走。想加速可以，想摆也可以，先别停。",
      "中等发挥。中等发挥连续三十天，会吓到人。",
      "没有高潮，所以也没有假装的高潮。挺好。",
      "估值不吵不闹，说明你也没有太胡闹。",
      "保持。保持这件事，听着没劲，做着有劲。",
      "今天像白开水。白开水能活，奶茶不能当饭。",
      "平稳复利中。请不要因为不够刺激就去刺激。",
      "和昨天握手言和。明天再谈加仓的事。",
      "平盘收官也可以。不是每天都要高潮。",
      "节奏在，人就在。人在，线就还在。",
      "没有暴击，有的是普通攻击。普通攻击会赢。",
      "今天份的「还行」。还行叠多了就是很好。",
      "市场没给你颁奖，也没罚你。继续上班。",
      "不亏不赚的一天，偏偏最容易被忘掉。别忘。",
      "原速。像走路，不像短跑。走路能到。",
      "你没有偷懒到被点名，也没有勤奋到被立牌坊。",
      "中规中矩。规矩有了，中不中以后再说。",
      "平平无奇的投入，是以后最想感谢的那种。",
      "今天的任务是：别把节奏弄丢。完成了。",
      "曲线在划直线。直线不帅，直线可靠。",
      "维持仓位。仓位还在，故事就能写下去。",
      "和最近打平。打平不是输，是还没退赛。",
      "日常款的一天。日常款才是主食。",
    ],
    slow: [
      "又偷懒？赶紧去学习，劳资蜀道山。",
      "节奏疏了。不是市场冷，是你手冷。",
      "估值在折价。折的不是行情，是今天的犹豫。",
      "这点投入，曲线看了想装没看见。",
      "比近几天淡。淡可以休息，淡太久叫消失。",
      "仓位在缩。你人还在，别跟着缩。",
      "偷懒被抓包了。抓包的是这根线，不是我。",
      "今天的你，有点像周末的作业：能拖就拖。",
      "少了。少的那一小时，不会自己长回来。",
      "行情转弱。弱的原因很简单：你没怎么动手。",
      "劳资看着这根线，有点想敲桌子。",
      "又开始神游？把手机扣上，先干二十分钟。",
      "折价了。不是世界抛弃你，是你先歇着了。",
      "投入变薄。薄如蝉翼的那种，风一吹就没。",
      "可以歇，但不能蒸发。蒸发了估值会记仇。",
      "今天有点飘。飘去哪了？短视频那边吗？",
      "节奏掉了。捡起来，不用捡全世界，捡一小段。",
      "偷懒可以有理由，曲线不听理由。",
      "这波回调，锅不在市场，在你的暂停键。",
      "人呢？资产还在等你上班。",
      "少干的那些，以后会变成稍微贵一点的后悔。",
      "别装忙。忙和刷，长得不像。",
      "估值给你打了折。打折的感觉，你自己清楚。",
      "今天心很野，手很懒。先管手。",
      "疏了就疏了。现在补一笔，还来得及装成没疏。",
      "曲线在问：你是出门了，还是灵魂出门了？",
      "再这么淡下去，鸡腿要改成白开水了。",
      "不是不行，是今天行得太少。",
      "懒是人权，连续懒是跟自己过不去。",
      "折价警告。警告很轻，明天可以当没听见——不建议。",
      "你最近有点像充电宝：看着在，其实没充电。",
      "投入不足。不足的部分，用十分钟也能先堵上。",
      "蜀道山可以，但山的那边还是得学习。",
      "今天的仓位轻飘飘。给它一点重量行不行？",
      "市场没抛弃你，你先把节奏抛弃了。",
      "偷一会儿可以。偷一整天，线会写进档案。",
      "这根线在冷笑。你要不要回去打它的脸？",
      "少了就补。补完再解释，解释给自己听。",
      "懒癌复发？药方很土：打开书，坐住。",
      "估值下跌不可怕，可怕的是你还觉得挺舒服。",
    ],
    overwork: [
      "最近学得有点多，一定要劳逸结合，奖励自己看一场电影吧。",
      "很拼。拼完请睡觉，估值喜欢活人。",
      "本金也是肉做的，别把明天的精力今天花光。",
      "再学下去曲线会谢你，颈椎会告你。",
      "投入已经很猛了。猛完要收回来，不是继续猛。",
      "你今天不是卷，是有点过了。过了也要吃饭。",
      "电影、散步、发呆，选一个。这叫保养资产。",
      "学得够多了。今晚的任务是：别再证明自己。",
      "曲线已经满意。现在轮到眼睛和腰满意。",
      "奖励自己。不是继续加码，是真的奖励。",
      "停一下不会死，连续超负荷才会。",
      "你已经把今天的本金快花完了。留一点给睡觉。",
      "优秀归优秀，优秀也要关灯。",
      "今天的量，够你骄傲，也够你早点躺下。",
      "劳逸结合不是鸡汤，是为了明天还能加仓。",
      "看场电影吧。曲线不会因为你看了两小时就翻脸。",
      "脑细胞不是无限续杯。去喝水，去吹风。",
      "你不是机器。机器还要散热呢。",
      "加鸡腿，加睡觉，不要再加任务了。",
      "收工。真正会的人，知道什么时候停。",
      "今天已经赢了。赢了还通宵，叫不会赢。",
      "过度投资也是一种挥霍。挥霍的是明天的你。",
      "放下。世界不会因为你少学一小时就塌。",
      "曲线在说可以了。你耳朵呢？",
      "去洗个澡。这比再看十页更像成年人。",
      "奖励清单：电影、好饭、早睡。三选一也行，全选更好。",
      "你今天对得起这根线了。现在去对得起枕头。",
      "别用透支证明勤奋。勤奋看的是明天还能不能来。",
      "学海无涯，但今天的岸就在旁边。上岸吃饭。",
      "够了够了。再够下去，明天会来收利息。",
    ],
    play: [
      "短视频吃掉的时间，曲线都记着，一笔一笔。",
      "游戏可以，当饭吃就不可以。",
      "刷得差不多了吧？差不多三个字，现在就能停。",
      "娱乐仓位有点重。重到估值开始皱眉。",
      "你不是在休息，你是在贴现。贴现很贵。",
      "再刷一集？那一集的价格，是今天的现价。",
      "玩可以，玩成主业，资产会辞职。",
      "手还在滑。滑的是时间，不是好运。",
      "即时满足很甜，甜完是折价。你尝过的。",
      "曲线在问：爽完了吗？爽完就回来。",
      "短视频不会爱你。估值倒是挺专一。",
      "玩太久了。不是道德审判，是算术题。",
      "屏幕亮着，仓位暗着。",
      "再给娱乐五分钟可以。再给两小时，就算你自愿打折。",
      "游戏开着，未来关着。选一个开着。",
      "消费型快乐很合法，连续合法就会变穷。",
      "你的拇指很勤奋。能不能把勤奋借给别的事？",
      "刷到这里的你，其实已经知道该停了。",
      "估值不反对快乐，反对的是快乐把正餐吃了。",
      "停。不是永远不玩，是今天已经玩过了。",
      "折价进行中。原因：太开心，开心错地方了。",
      "娱乐结束后，还剩一点本金。别全部上交。",
      "短视频的算法很懂你。你要不要也懂一下自己？",
      "玩物可以，丧志就免了。现在是临界点。",
      "把手机翻面。翻面这一秒，比任何计划都便宜。",
    ],
    empty: [
      "这一栏还没有持仓。本金倒是在，等你下单。",
      "空白不是失败，是还没开始。开始只要一笔。",
      "曲线想长，还差你随手记的一小段。",
      "这里空着。空着不可怕，一直空着才像没这回事。",
      "资产账户开好了，第一笔投资呢？",
      "还没有持仓。你人已经在了，差一个动作。",
      "空白页。第一笔不需要完美，需要发生。",
      "这一栏在等。等的不是灵感，是你坐下来。",
      "零持仓。零也可以是起点，别让它当终点。",
      "还没动。动一下，线就会原谅你的迟。",
      "本金每天到账。不用完，午夜清零，不讲人情。",
      "空仓观望可以。观望太久，观成了旁白。",
      "这里还是荒地。种一小时，就是开荒。",
      "没有记录，不等于没有生活。但线只认记录。",
      "第一笔可以很短。短到你都不好意思，但算数。",
      "估值还没出生。你给它起个头吧。",
      "空白的好处是：怎么画都是新高。",
      "还没持仓。那今天的第一笔，就当剪彩。",
      "账户是空的。空的账户最怕的是你也空着过。",
      "开始吧。开始这件事，比方向更着急。",
    ],
    waste: [
      "最近一个工作日空仓，市场在给你冷脸。",
      "工作日交白卷，估值会记，记性还挺好。",
      "空了一天。空不是休息，休息会写「休息」。",
      "那个工作日消失了。消失的东西，补不回日期。",
      "行情在折价。因为有一天，你完全没出现。",
      "空白的工作日，是最贵的那种消费。",
      "缺席会被标价。标价很难看，但诚实。",
      "那天的本金清零了。清零不会通知你，只会反映在线上。",
      "空仓不是策略，是忘了上场。",
      "工作日也可以摆。摆完会在这根线上签字画押。",
      "缺了一天。今天多做一点，是道歉，也是补票。",
      "市场不骂人，只打折。打折已经够呛。",
      "那天空着，今天还在。还在就还有机会补脸。",
      "白卷事件。当事人：你。处理意见：现在就记一笔。",
      "资产还在，信用差点。信用靠今天修。",
      "空仓的工作日会在复盘里闪光——那种不想看的光。",
      "缺席过一次就算了。别让它变成风格。",
      "折价来自空白。填上今天，空白会小一点。",
      "那天你把 24 小时全花了，花在看不见的地方。",
      "工作日归零，周末都替你觉得冤。",
    ],
    weekend: [
      "周末行情很平。平着过，也算一种持仓。",
      "周末可以慢。慢不是无，是换挡。",
      "这两天市场打盹。你打盹可以，别睡死。",
      "周末允许松一点。松完记得还在。",
      "休市不等于销户。人还在就行。",
      "周末的平，是为了周一还认识自己。",
      "可以躺。躺的时候给休息记一笔，别假装没活。",
      "周末不考核爆发，考核你还在不在场。",
      "平盘周末。电影、太阳、朋友，都比自责值钱。",
      "这两天不必证明什么。证明留给工作日。",
      "周末的估值很懒。懒得刚刚好。",
      "休息如果发生了，就大大方方记下来。",
      "周末可以是保养日，不是蒸发日。",
      "行情很平。你也可以平，平里留一点清醒。",
      "周六周日不是罪。空着过才像有点罪。",
      "低波动周末。去走走，别只在被窝里低波动。",
      "周末的任务：活着，顺便喜欢自己一点点。",
      "可以不卷。不卷的时候，别把脑子交给短视频托管。",
      "平。平得像周末该有的样子。",
      "歇着。歇是投资未来的气，不是认输。",
    ],
    dawn: [
      "早起的鸟儿有虫吃，早起的你，困得要死。",
      "天还没亮透。你亮了，先别亮着玩手机。",
      "五点的世界很安静。安静适合干一件正经事。",
      "新的一天到账了。本金新鲜，别第一口就挥霍。",
      "这么早？行，既然醒了，就别躺回去假装没醒。",
      "晨光很贵。贵在别人还在睡，你已经能开始。",
      "眼睛还没睁圆。先睁圆，再决定今天是谁。",
      "凌晨的你很英勇。英勇完请喝水，别只英勇。",
      "世界还没上班。你要不要偷偷先上一会儿？",
      "早起本身已经加分。加完分，去做一件小事兑现。",
      "困是真的，开始也可以是真的。两者可共存。",
      "天刚灰。灰的时候做事，比中午清静。",
      "你起得很早。早起的意义不是发朋友圈，是占时间。",
      "本金刚到。花第一笔在值得的地方，后面会顺。",
      "清晨的懒，比晚上的懒更可惜。晚上至少忙过。",
      "鸟在叫。你在不在，取决于下一小时。",
      "日出不等人。你也不用等完美状态。",
      "这么早还睁眼，说明今天有戏。别把戏看完就睡回去。",
      "黎明时分的选择很简单：再躺，或先动。",
      "早。早到可以重新做人一小会儿。",
    ],
    morning: [
      "上午还长。长的意思是：来得及，也来得及浪费。",
      "早饭过了吗？过了就开工，没过先吃饭。",
      "一天刚开始。刚开始的人，最不该先打开短视频。",
      "上午是黄金时段。黄金拿去刷，就变黄铜。",
      "脑子还算清。趁清，先干最不想干的那件。",
      "新的一天，旧的你。要不要升级一下补丁？",
      "早晨的计划都很美。美完要落地，落地只要二十分钟。",
      "阳光在，人也该在。在座位上那种。",
      "上午不加速，下午就会找补，补得很疼。",
      "一天的坡，早上最缓。现在爬，比晚上省力。",
      "还早。还早不是继续躺的理由，是从容的理由。",
      "咖啡因生效前，先做一件不用灵感的事。",
      "上午的你如果靠谱，晚上的你会谢谢你。",
      "别把早上过成预告片。直接播正片。",
      "本金还很厚。厚的时候最容易觉得「反正还早」。",
      "开学的感觉有没有？没有也装有，装着装着就真了。",
      "上午适合学习。适合的意思是：现在去。",
      "一天的第一笔投资，决定后面会不会心虚。",
      "早高峰在路上。你的高峰，能不能也在脑子里？",
      "别等状态。状态是做起来才有的。",
      "上午浪费掉，全天都会带着一点脏。",
      "起来了就好。好下一步：把第一件事做完。",
      "晨间可以慢热。慢热不是不热。",
      "今天的故事还没写。第一句，现在就能写。",
    ],
    noon: [
      "中午了。吃过没？没吃先吃，别用学习当节食。",
      "日头正顶。顶得住的人，会先放下叉子再拿书——或者反过来。",
      "午饭是投资。空肚子的勤奋，会在下午罢工。",
      "过午。过午的人容易昏。昏就站起来走两步。",
      "上午如果没动，现在动还来得及装成「今天有做事」。",
      "午饭后的困是真的。困完睡十五分钟，比硬撑强。",
      "中场。中场可以休息，也可以把上半场没做的补上。",
      "太阳最大的时候，人最小的愿望往往是躺平。理解，但不推荐全天躺。",
      "吃好。吃好的人下午才像个人。",
      "正午的选择：补觉，或补一小时。别补短视频。",
      "一天过半。过半了还空着，就有点说不过去。",
      "午饭别刷着吃。胃和算法，留一个在线就行。",
    ],
    afternoon: [
      "下午是考验意志的时段。意志不在，可以先假装在。",
      "困、散、想走。正常。正常完，再坐二十分钟。",
      "下午的时间很滑。滑走之前，先按住一件事。",
      "后半段开始了。前半段怎样都好，后半段还能救。",
      "阳光变斜。斜的时候最适合把难的事收尾。",
      "下午茶可以有。下午茶代替工作，就没了。",
      "还早？不早了。但也不晚。正好。",
      "精力在下山。下山前再推一把，晚上会轻松。",
      "下午容易废。解药是很小的任务，不是很大的自责。",
      "时钟过了中点。你的投入过中点了吗？",
      "把一件事做到能交差。交差比完美可爱。",
      "下午的你如果还在，晚上就可以少一点心虚。",
    ],
    evening: [
      "晚上了。晚上适合收网，不适合重新开一局通宵。",
      "天黑了。黑了也可以学，但要给睡觉留门。",
      "晚饭过后是岔路：继续当人，或变成拇指。",
      "夜晚的娱乐很香。香完看一眼白天的线，再决定份量。",
      "今天能收的，现在收。收不完的，留给明天，别硬刚。",
      "晚上加鸡腿可以。加完鸡腿加任务，量力。",
      "灯亮着。亮着做事叫加班，亮着刷叫耗电。",
      "一天快结账了。结账前还能记一笔像样的。",
      "晚间档。电影、散步、最后一小时学习，选得明白就好。",
      "别把晚上过成垃圾时间。垃圾时间会变成习惯。",
      "如果今天已经很拼，晚上请休息。如果没有，晚上是补考。",
      "月亮不催你。催你的是明天的早晨。",
      "夜宵可以，通宵免谈。免谈是为了明天的现价。",
      "晚上的你比较诚实。诚实一点：今天到底做成了什么？",
      "收工前十分钟，比计划里的两小时更常发生。",
      "夜色适合复盘，不适合自我审判。复盘完就关灯。",
      "今晚必须加鸡腿——如果白天配得上的话。",
      "把明天要做的第一件事写下来。写完就可以玩一会儿。",
      "傍晚的风是免费的。免费的休息，比付费的短视频干净。",
      "夜还长。长不代表要把它填满。",
    ],
    night: [
      "这么晚了还在。在学习就算，在刷就有点亏。",
      "深夜的世界很小：你、屏幕、以及明天的黑眼圈。",
      "该睡了。睡是明天的加仓，不是认输。",
      "凌晨的勤奋很帅，帅完会在上午失踪。",
      "还没关灯？关灯。曲线喜欢睡饱的人。",
      "夜猫可以，夜猫也要有归巢时间。",
      "明天的上午，正在这儿偷你的睡眠。",
      "困了就睡。硬撑出来的那一小时，质量很差。",
      "深夜情绪放大。放大的事先不决策，先睡觉。",
      "你不是唯一醒着的人。但你可以直接不当那个醒着的人。",
      "十一点后的时间，看起来像白捡，其实是高利贷。",
      "枕头在叫你。比任何通知都重要。",
      "再看一集？这一集的利息，明天上午还。",
      "熬夜换来的「多学一点」，常常被「全天浑」抵消。",
      "关屏。世界会在你睡着的时候自己转。",
      "今天到此为止。到此为止是一种能力。",
      "黑眼圈不是勋章。勋章是明天还能清醒地来。",
      "夜深了。深的地方不适合做人生决定，适合躺下。",
      "如果你在赶，赶完就睡。如果在逛，现在就可以睡。",
      "睡眠是休养栏的大单。别把大单让给短视频。",
      "明天还要做人。做人需要关机。",
      "这么晚了还盯着估值？估值希望你去睡觉。",
    ],
    books: {
      mind: {
        rising: [
          "学识这栏在涨。脑子被你当肌肉练了。",
          "最近学得多。今晚可以看场电影，名正言顺。",
          "书页或题目，总之你没在假装努力。",
          "学识加速。加速的人有资格加鸡腿。",
          "脑子今天上班了。上班的脑子值得好饭。",
          "这一栏抬头了。抬头的原因很土：你坐下了。",
          "比近几天更像学生。像就对了。",
          "知识仓位加了。加完记得伸个懒腰。",
          "学识曲线认你。认的是时长，不是宣言。",
          "这波学习是真的。真的就可以小小骄傲。",
          "头脑在复利。复利很慢，但你已经在路上。",
          "学了。学了就会涨，涨了也要睡觉。",
        ],
        slow: [
          "学识这栏有点饿。喂它一小时，别喂短视频。",
          "书在，人呢？人去刷了吗？",
          "脑子今天几乎没开工。开工只要打开。",
          "学识在折价。折价药方：坐住，开始，二十分钟。",
          "这一栏变淡了。淡的反义词不是爆学，是回来。",
          "学生的主业呢？主业不能只存在课程表上。",
          "学识仓位变轻。给它一本打开的书。",
          "最近学得少。少不可怕，装没看见才可怕。",
          "题目不会自己消失。你消失倒是挺快。",
          "学识在敲桌子。敲得很轻，但敲了。",
          "把手机放到另一个房间。学识会谢谢你。",
          "这一栏需要你。需要的不是灵感，是屁股。",
        ],
        flat: [
          "学识按原速走。原速很土，土能考过。",
          "今天的学习像日常饭。饭不刺激，饭保命。",
          "学识既没爆发也没断。这就已经赢过很多天。",
          "平稳输入中。输入这件事，比顿悟常见。",
          "这一栏很安静。安静地学，也是学。",
          "和近几天差不多。差不多就继续，别找高潮。",
          "学识在慢慢变沉。沉是好事。",
          "今天没有开窍，有的是页码。页码也算。",
          "维持学习仓。仓还在，考前会感谢。",
          "平盘学习日。平盘叠起来，就是会的人。",
        ],
        overwork: [
          "学得有点猛。猛完看场电影，这是保养脑子。",
          "学识已经吃饱了。再喂会撑，撑了明天消化不了。",
          "书可以合上。合上不是放弃，是让它进长期记忆。",
          "脑子过热。过热的处理：走路、洗澡、关机。",
          "今天的学习额度用满了。满了就去当普通人。",
          "再盯下去字会跑。字跑了你还在，不值。",
          "学识栏说：可以了，去生活一会儿。",
          "劳逸结合。逸不是堕落，是为了还能学。",
        ],
      },
      body: {
        rising: [
          "健康这栏在涨。身体开始相信你说的话了。",
          "动了。动了就会涨，涨了别忘了拉伸。",
          "最近有在练。今晚蛋白质可以光明正大。",
          "身体仓位加了。加完喝水，别只加鸡腿。",
          "出汗了吧？出汗的日子，估值会点头。",
          "健康在加速。加速的人走路都会骄傲一点。",
          "你没有只在脑子里健身。少见，表扬。",
          "这一栏抬头，说明你离开椅子了。",
          "练了就吃好。吃好不是放纵，是补给。",
          "身体记得每一趟。记得比你自己清楚。",
          "健康曲线认你。认的是次数，不是会员卡。",
          "这波是真练。真练可以洗澡洗很久。",
        ],
        slow: [
          "健康这栏有点闲。闲到骨头都想出门。",
          "身体在打折。打折原因：椅子贴得太紧。",
          "最近没怎么动。动十分钟也算，零才尴尬。",
          "健康仓位变轻。下楼一趟，仓位就有声音。",
          "肌肉在问：你是把我忘了，还是把我当装饰？",
          "这一栏饿了。喂它走路、跳绳、随便什么。",
          "坐太久了。估值不看你的腰，腰自己会看。",
          "健康在冷笑：又打算明天开始？",
          "身体不会被计划感动，只会被出门感动。",
          "动一动。不是塑造身材，是把今天救回来一点。",
          "健康折价中。药方很土：换上能走的鞋。",
          "这一栏需要出汗，哪怕一点点。",
        ],
        flat: [
          "健康按原速。原速可以是散步，不必每天爆汗。",
          "身体仓位还在。在就比「想练」强。",
          "今天的健康像日常。日常才能一直有健康。",
          "没创纪录，也没躺平。骨头会接受这个答案。",
          "维持活动量。维持比偶尔猛练更像生活。",
          "健康很平。平着动，动着平，挺好。",
          "这一栏没有大新闻。没有新闻的锻炼最可持续。",
          "和近几天差不多。差不多就继续出门。",
          "身体在保值。保值靠的是你还肯动。",
          "平稳的健康日。平稳到你都忘了，其实刚好。",
        ],
        overwork: [
          "练挺猛。猛完要吃、要睡，别只猛。",
          "健康已经加够仓了。再加就变成跟自己较劲。",
          "今天的量够了。够了还补一趟，明天会来收腿。",
          "拉伸、洗澡、睡觉。这三件事现在比再练一组重要。",
          "身体不是永远能加杠杆。杠杆今晚收掉。",
          "出了很多汗。汗可以停了，水要继续。",
          "健康栏说：可以了，去当会休息的人。",
          "恢复也是训练。今晚请训练恢复。",
        ],
      },
      craft: {
        rising: [
          "创作这栏在涨。东西被你做出来了，不是只被想出来。",
          "最近有产出。产出的人今晚可以得意，小声的。",
          "做了。做了就会涨，涨了也要存个档。",
          "创作加速。加速的人有资格看场无关的电影。",
          "草稿变成了更像东西的东西。这就是涨。",
          "这一栏抬头，说明你没有只在备忘录里天才。",
          "手在干活。手干活的时候，脑子会老实一点。",
          "创作仓位加了。加完可以离开作品一会儿。",
          "你最近不是在「准备创作」，是在创作。",
          "作品在变沉。沉是真的，灵感是漂的。",
          "这一栏认你。认的是完成，不是人设。",
          "做出来了就好。好就可以吃好的。",
        ],
        slow: [
          "创作这栏有点停摆。停摆常从「再想想」开始。",
          "作品在等。等的不是更好的点子，是你打开文件。",
          "最近没怎么做。做十分钟也算开工，零才叫卡。",
          "创作在折价。因为今天几乎没有痕迹留下。",
          "灵感没来。没来也先干，干着它有时会来。",
          "这一栏饿了。喂它一行、一笔、一块，都行。",
          "别等完美。完美最爱的就是你一直等。",
          "创作仓位变轻。轻到只剩想法，想法不记账。",
          "手闲着。闲着手会去刷，刷完更闲。",
          "打开它。打开比想清楚更接近完成。",
          "这一栏需要痕迹。痕迹可以很难看。",
          "创作在敲：你是作者，还是评论区观众？",
        ],
        flat: [
          "创作按原速。原速可以是很小的一笔，只要发生。",
          "今天没有神作，有的是还在做。还在做就行。",
          "创作很平。平着推进，比等爆发健康。",
          "这一栏没有高潮。没有高潮的日子里，作品会长。",
          "维持制作。维持比偶发天才更像作者。",
          "和近几天差不多。差不多就继续碰那个文件。",
          "产出稳定。稳定听着像加班，其实是手艺。",
          "创作在保值。保值靠你还肯打开。",
          "小小做一点。一点叠起来，会变成别人以为的突然。",
          "平盘创作日。平盘也能交稿。",
        ],
        overwork: [
          "做得有点猛。猛完离开作品，作品会自己醒一醒。",
          "创作已经很多了。再熬，明天会看不懂自己。",
          "保存、离开、去生活。生活是下一笔的材料。",
          "今天的量够了。够了还改，会改坏。",
          "手可以停。停不是弃坑，是让眼睛复位。",
          "创作栏说：可以了，去看别人的作品当休息。",
          "过劳的创作会发苦。苦之前先收工。",
          "奖励自己：不碰它一晚。明天它还在。",
        ],
      },
    },
  },
  en: {
    rising: [
      "Above the recent pace. Tonight you have earned the good meal.",
      "You added to the position. The tape noticed. So should you.",
      "Faster than the last few days. Keep it, don't perform it.",
      "The curve is up because you were. Not luck.",
      "A little pride is allowed. A little more work tomorrow is better.",
      "You beat the average. Celebrate with food, not another tab.",
      "This is you, compounding on purpose.",
      "The line is honest: you actually showed up extra.",
    ],
    flat: [
      "Same pace as recently. Boring. Compounding loves boring.",
      "No spike, no collapse. Stay.",
      "A standard day. Stack enough of these and it becomes a life.",
      "Still in. Still counts.",
      "Holding the rhythm. That's the whole game on quiet days.",
      "Unspectacular input. Future-you collects the interest.",
    ],
    slow: [
      "Below the recent pace. The discount is your hesitation, not the market.",
      "A little lazy? Get up. The line is watching.",
      "Thin input today. Thin does not grow back by itself.",
      "You drifted. Twenty minutes would already change the sentence.",
      "The tape marked you down. It is not personal. It is arithmetic.",
      "Come back. You don't need a whole day. You need a start.",
    ],
    overwork: [
      "You have done a lot. Rest is part of the position now.",
      "Enough. Sleep is tomorrow's contribution.",
      "The curve is happy. Your neck is not. Stop.",
      "Reward yourself with a film, a walk, a shutdown. Not another task.",
      "Over-investing today spends tomorrow. Close the book.",
    ],
    play: [
      "Too much cheap dopamine. The price is already taking notes.",
      "Games are fine. Games as a meal are not.",
      "Put the phone face down. That second is cheaper than any plan.",
      "Fun spent the principal. Come back before midnight clears it.",
    ],
    empty: [
      "No position yet. The capital is still here, waiting for a first fill.",
      "Blank is not failure. Blank plus never is.",
      "One short log and the curve can start.",
      "The account is open. The first hour is the ribbon-cutting.",
    ],
    waste: [
      "A weekday was empty. The market remembers absences.",
      "A blank workday is an expensive way to rest.",
      "You missed a session. Repair it today, even a little.",
      "The discount is from a zero. Fill today so the zero shrinks.",
    ],
    weekend: [
      "Weekend tape is quiet. Quiet is allowed. Vanishing is not.",
      "Slow is a gear, not an exit.",
      "Rest if you rest. Log it. Don't pretend the day didn't happen.",
      "No need to prove anything until Monday. Stay in the room.",
    ],
    dawn: [
      "Early bird gets the worm. Early you can barely stand. Start small.",
      "The day just credited capital. Don't spend the first minute on a feed.",
      "The world is still asleep. You could do one real thing before it wakes.",
      "So early. If you're up, don't lie back down as a personality.",
    ],
    morning: [
      "The morning is long. Long enough to begin, long enough to waste.",
      "Do the thing you least want, while the brain is still kind.",
      "Don't let the morning become a trailer. Play the film.",
      "First investment of the day decides how guilty the night feels.",
    ],
    noon: [
      "Eat. Hungry discipline goes on strike at 3.",
      "Midday. If the morning was empty, this is still a rescue window.",
      "A short nap beats a long scroll.",
    ],
    afternoon: [
      "Afternoon is where willpower leaks. Do twenty minutes anyway.",
      "The day is past halfway. Yours can still be.",
      "Finish one thing well enough. Perfect can wait.",
    ],
    evening: [
      "Evening is for closing loops, not opening a midnight raid.",
      "If you already worked, rest. If not, this is the makeup exam.",
      "Log one decent stretch before the day settles.",
      "Write tomorrow's first task. Then you can play a little.",
    ],
    night: [
      "It's late. Sleep is tomorrow's buy. Staying up is a loan.",
      "Midnight hours look free. They charge interest in the morning.",
      "Shut it down. The curve prefers you conscious tomorrow.",
      "If you're finishing, finish and sleep. If you're browsing, just sleep.",
    ],
    books: {
      mind: {
        rising: ["Mind is up. You treated the brain like a muscle."],
        slow: ["This book is hungry. Feed it an hour, not a feed."],
        flat: ["Steady study. Unfashionable, and it works."],
        overwork: ["You've studied enough. A film is maintenance, not guilt."],
      },
      body: {
        rising: ["Body is up. You actually moved."],
        slow: ["This book is bored. Ten minutes outside still counts."],
        flat: ["Same activity as recently. That's how bodies last."],
        overwork: ["Hard session. Eat, stretch, sleep. No extra heroics."],
      },
      craft: {
        rising: ["Craft is up. You made it, you didn't just imagine it."],
        slow: ["The file is waiting. Waiting is not work."],
        flat: ["Quiet making. Quiet making becomes a body of work."],
        overwork: ["Leave the piece alone tonight. It'll look clearer tomorrow."],
      },
    },
  },
};

function collectPool(bank, mood, bookId, time, todayH, isToday) {
  const pool = [];
  const push = (arr, weight = 1) => {
    if (!arr?.length) return;
    for (let i = 0; i < weight; i++) pool.push(...arr);
  };

  push(bank[mood] || bank.flat);

  const book = bank.books?.[bookId];
  if (book?.[mood]) push(book[mood], 2);

  if (!isToday) return pool;

  const early = todayH < 0.35 && (time === "dawn" || time === "morning");
  if (early) {
    push(bank[time], 3);
    if (time === "dawn") push(bank.morning, 1);
  } else if (time === "night") {
    push(bank.night, 2);
  } else if (bank[time]) {
    push(bank[time], 1);
  }
  return pool;
}

export function pickEvalLine({
  mood,
  bookId,
  hour,
  todayH = 0,
  consumeH = 0,
  isToday = true,
  dateISO = "",
  lang = "zh",
  price = "",
} = {}) {
  const bank = LINES[lang] || LINES.zh;
  const evalMood = resolveMood(mood, todayH, consumeH);
  const time = timeBucket(Number(hour) || 0);
  const pool = collectPool(bank, evalMood, bookId, time, todayH, isToday);
  const fallback = (LINES.zh[evalMood] || LINES.zh.flat);
  const line = hashPick(pool.length ? pool : fallback, `${dateISO}|${bookId}|${evalMood}|${isToday ? time : "past"}`);
  return String(line || "").replaceAll("{price}", String(price));
}

export function lineCount(lang = "zh") {
  const bank = LINES[lang] || LINES.zh;
  let n = 0;
  const walk = (obj) => {
    if (Array.isArray(obj)) n += obj.length;
    else if (obj && typeof obj === "object") Object.values(obj).forEach(walk);
  };
  walk(bank);
  return n;
}
