import assert from "node:assert/strict";
import worker, { validateInput, cleanOutput } from "../cloud/coach/worker.js";
const input={mode:"yesterday",blocks:[{id:"a",start:1000,end:2000,kinds:["STUDY"],name:"学习"}]};
assert.throws(()=>validateInput({mode:"bad",blocks:[]}));
assert.throws(()=>validateInput({...input,blocks:[{...input.blocks[0],end:0}]}));
const clean=cleanOutput({summary:"one",events:[null,{recordId:"unknown"},{recordId:"a",knowledgeIds:["sleep"],sources:[{url:"https://untrusted.test"}]}],habits:["meal_walk","evil","meal_walk"]},validateInput(input));
assert.equal(clean.events.length,1);assert.equal(clean.events[0].sources[0].url,"https://www.cdc.gov/sleep/about/");
assert.deepEqual(clean.habits,["meal_walk"]);
const env={DEEPSEEK_API_KEY:"test-not-a-real-key",DEEPSEEK_MODEL:"test-model",APP_ACCESS_TOKEN:"a".repeat(32),AI_RATE_LIMIT:{limit:async()=>({success:true})}};
const request=(body=input,token=env.APP_ACCESS_TOKEN,origin="capacitor://localhost")=>new Request("https://worker.test/analyze",{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${token}`,Origin:origin},body:JSON.stringify(body)});
assert.equal((await worker.fetch(request(),{})).status,503);
assert.equal((await worker.fetch(request(input,"wrong"),env)).status,401);
assert.equal((await worker.fetch(request(input,env.APP_ACCESS_TOKEN,"https://attacker.test"),env)).status,403);
assert.equal((await worker.fetch(request({}),env)).status,400);
assert.equal((await worker.fetch(request(),{...env,AI_RATE_LIMIT:{limit:async()=>({success:false})}})).status,429);
let sent;
globalThis.fetch=async(url,options)=>{sent=JSON.parse(options.body);return Response.json({choices:[{finish_reason:"stop",message:{content:JSON.stringify({summary:"完成了学习",events:[],habits:[]})}}]});};
const response=await worker.fetch(request(),env);
assert.equal(response.status,200);assert.equal(response.headers.get("Access-Control-Allow-Origin"),"capacitor://localhost");
assert.equal((await response.json()).summary,"完成了学习");
assert.equal(sent.response_format.type,"json_object");
assert.equal(sent.messages[0].content.includes("不能"),true);
globalThis.fetch=async()=>Response.json({choices:[{finish_reason:"length",message:{content:"{}"}}]});
assert.equal((await worker.fetch(request(),env)).status,502);
globalThis.fetch=async()=>Response.json({choices:[{finish_reason:"stop",message:{content:"not json"}}]});
assert.equal((await worker.fetch(request(),env)).status,502);
console.log("worker authentication, validation, rate limit and source whitelist tests passed");
